/******* Return the Application Reference Number generated by Curam, given the Case_Worker ID and the interval in minutes,
         given by [SYSDATE - LENGTH_OF_INTERVAL] in which to search the CASEHEADER, INTAKEPROGRAMAPPCASELINK and INTAKEPROGRAMAPPLICATION tables. 
         If no Application Reference Number is found (or an error occurs), 'NULL' is returned **************************************/
         
CREATE OR REPLACE FUNCTION GET_APP_REF (CASE_WORKER IN string, LENGTH_OF_INTERVAL IN NUMBER) RETURN NUMBER
AS
BEGIN /* FUNCTION */
DECLARE
  APP_CASEREF  VARCHAR2(20);
  BEGIN /* EXECUTION */
--    dbms_output.put_line('=====================================================================================================================================================================================================================================');
      select CASEREFERENCE INTO APP_CASEREF from CASEHEADER where CASEHEADER.CASEID = (select INTAKEPROGRAMAPPCASELINK.CASEID from INTAKEPROGRAMAPPCASELINK where 
        INTAKEPROGRAMAPPCASELINK.INTAKEPROGRAMAPPLICATIONID = (select INTAKEPROGRAMAPPLICATION.INTAKEPROGRAMAPPLICATIONID from INTAKEPROGRAMAPPLICATION where INTAKEPROGRAMAPPLICATION.ENTEREDBYUSER = CASE_WORKER
          AND INTAKEPROGRAMAPPLICATION.CREATEDON >= (SYSDATE - LENGTH_OF_INTERVAL/(60.0 * 24.0))));
--    dbms_output.put_line('===================================CASEID FOUND = ' || APP_CASEREF || ' =================================================================');
--    dbms_output.put_line('=====================================================================================================================================================================================================================================');
      RETURN APP_CASEREF;
      EXCEPTION
           WHEN others THEN
              RETURN NULL;
  END; /* EXECUTION */
END; /* FUNCTION */
/

/* TO execute the GET_APP_REF function, use either of the two methods below (remember to execute "SET SERVEROUTPUT ON;" before running the first */
/* Method 1 */
SET SERVEROUTPUT ON;
declare  v_ret varchar2(100);
BEGIN
  v_ret := GET_APP_REF ('GHNCYT@gmail.com',10000.1);
  dbms_output.put_line(TO_CHAR(v_ret));
END;
/

/* Method 2 */
select GET_APP_REF ('GHNCYT@gmail.com', 18.1) from dual;

/* Use this statement to first find a caseworker ID to test with and a time interval from which to search */          
select ENTEREDBYUSER, TO_CHAR(CREATEDON, 'yyyy/mm/dd hh24:mi:ss'), TO_CHAR(LASTWRITTEN, 'yyyy/mm/dd hh24:mi:ss') 
          from INTAKEPROGRAMAPPLICATION where INTAKEPROGRAMAPPLICATION.CREATEDON >= (SYSDATE - 2000.0/(60.0 * 24.0)) order by CREATEDON desc;
